import "./globals.css"
export const metadata = {
  title: "Peworld",
  description: "Generated by create next app",
};

import {cookies} from 'next/headers'

const getCookie = async (name) => {
  return cookies().get(name)?.value ?? '';
}
const token = await getCookie('token')

import BaseLayout from './base-layout'
export default function RootLayout({ children }) {  
  return (
    <html lang="en">      
      <body>
        <BaseLayout token={token}>{children}</BaseLayout>
      </body>
    </html>
  );
}
